### ISSUE TITLE
^C has no effect in macOS

### ISSUE THREAD

**Issue by bolknote** [oleg-st/DevSync#1]
dotnet /usr/local/Cellar/devsync/0.1/DevSync.dll --realsync . --deploy
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^X^X^X^X^X^C^C^C^C^C^C^C^C^C^C^C

nothing happened

**Comment by oleg-st** [comment]
Fixed, thanks for reporting.
